# Use a base Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all contents of the folder (model) to the container's working directory
COPY . /app/

# Install system dependencies for OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create directories to store models and logs if they don't exist
RUN mkdir -p /app/models /app/logs

# Environment variable that controls the automatic call to registration
ENV AUTO_REGISTER=true

# Command to execute the main script (model_init will automatically call model_reg if AUTO_REGISTER is true)
CMD ["python", "model_init.py"]
