# Use Python as base
FROM python:3.10

RUN apt-get update && apt-get install -y libgl1
# Create the directory for MLflow artifacts
RUN mkdir -p /mlflow/artifacts

# Create working directory inside the container
WORKDIR /app

# Copy files
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy API and frontend code
COPY . /app/

# Expose API port
EXPOSE 5001

# Command to run the API
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "app:app"]
